### ISSUE TITLE
Bundle Support

### ISSUE THREAD

**Issue by bassrock** [KrauseFx/fastlane#139]
Right now I have my fastlane toolset defined in a Gemfile for use with bundler. This is because between different versions of other tools (Cocoapods *cough*) it is needed to maintain consistency and true independence on different machines. 

The bundle installs fine, but when I run ```bundle exec fastlane lane``` commands like ```ipa``` or ```pod``` etc, are not found.

I think a good idea would be to set an environment variable in the fastlane file to prefix all commands with or to use bundler to run commands. Or maybe this already exists and I am missing it.  Would be glad to look into adding this support as well if it honest exist already.

**Comment by esttorhe** [comment]
@bassrock that's weird; I do have the same setup as you and I'm able to use `bundle exec fastlane inhouse` for example; where `inhouse` is a lane that downloads the certificates and provisioning profiles, runs the tests, generates the ipa and uploads it to `HockeyApp` while sending message to `Slack`.

Only tool I was not able to use was `deliver` but it was because of an issue where it was always trying to upload to the `AppStore` versus making the `beta` upload.

**Comment by bassrock** [comment]
@esttorhe So I thought the same thing as it was working on my local machine. But it fails on my build machine. I noticed the difference is on my local machine I have the bundle, but I also have the tools installed system wide.

Do you also have them installed system wide?

**Comment by esttorhe** [comment]
mmm, weirdly enough I do have them now…
Wondering why though; in theory the only one I had globally installed was `sigh` but now I do have all the `fastlane tools` :/

**Comment by KrauseFx** [comment]
@bassrock A lot of users are using `fastlane` with Bundler just fine. They'll add a comment here soon.

**Comment by dtrenz** [comment]
Have you tried setting the bundle path/bin as part of your bundle build step? I've had issues with using shared gem/bundle resources on build machines before.

```sh
bundle --path=.bundle --binstubs=bin
```

**Comment by bassrock** [comment]
@KrauseFx my bad I noticed it adds the gems to the path so i must have something else wrong. Anyways thanks!
