### ISSUE TITLE
[Feature] Provide different Appfile configs for each lanes

### ISSUE THREAD

**Issue by KrauseFx** [KrauseFx/fastlane#146]
As many apps use different bundle identifiers per environment (beta, app store), there should be a way to  define that.

**Current `Appfile`:**
```ruby
app_identifier "net.sunapps.1"
apple_id "felix@sunapps.net"
# team_id "Q2CBPJ58CC"
```

**Suggestion:**
```ruby
app_identifier "net.sunapps.1"
apple_id "felix@sunapps.net"
team_id "Q2CBPJ58CC"

for_lane :beta do
  app_identifier "net.sunapps.1.beta"
end

for_lane :enterprise do
  app_identifier "enterprise.com"
end
```

The value **inside** the blocks will be used if given, otherwise the value outside.

What do you think?

**Comment by BrettThePark** [comment]
YES!!!  It would also be great if a "Root" folder could be specified for each lane. For example, I have one large workspace which has five different projects in different folders. I would love to be able to specify the default folder for each lane that way I could have one Fastlane file for the whole workspace. 

To facilitate the workspace right now, I need three different fastlane instances with long relative references and custom scripts to do simple things like increment the build all because the fastlane pipeline is not in the same folder as the project.

**Comment by ekinsol** [comment]
A related suggestion would be the ability to set the app_identifier as an argument.

Ex:
fastlane beta -app_identifier com.random.app

This would be very welcome in a white label setup

**Comment by KrauseFx** [comment]
This make sense and might make the setup easier @ekinsol

**Comment by ekinsol** [comment]
@KrauseFx indeed, but as you suggested on twitter, might be overkill.

An easy way to get custom app identifiers into the flow:

#open a file that contains a single line with the app identifier 
customAppID = open("app_identifier_file").read

With some extension this is enough to drive various lanes from Jenkins etc

**Comment by fabiomassimo** [comment]
@ekinsol I'm not sure the fastlane CLI should include such an option like `app_identifier`. The fastlane platform already gives you a quick way to define a new lane that now is driven with the new `Appfile` configuration loader [feature](https://github.com/KrauseFx/CredentialsManager/pull/4).

**Comment by KrauseFx** [comment]
This is solved now, thanks to the awesome @fabiomassimo :rocket: Thanks again :smile:
