### ISSUE TITLE
Exit status of command was 256 instead of 0.

### ISSUE THREAD

**Issue by sneps85** [KrauseFx/fastlane#271]
Exit status of command 'set -o pipefail && ipa build  --verbose | xcpretty' was 256 instead of 0.

This is the error i get. What is wrong?

**Comment by KrauseFx** [comment]
That means your build failed. Please share your complete output so I can help you!

**Comment by snarkdogg** [comment]
I get this same error when running under Jenkins (on Mac OSX Yosemite). Here is the log:

12:34:26 [CoreApp_iOS_DevelopFastlane] $ /bin/sh -xe /var/folders/f4/58tc3f2n7bqc2yrpqz5t24t80000gn/T/hudson4977111837204743222.sh
12:34:26 + fastlane develop
12:34:26 [12:34:26]: -------------------------------------------------
12:34:26 [12:34:26]: --- Step: Verifying required fastlane version ---
12:34:26 [12:34:26]: -------------------------------------------------
12:34:26 [12:34:26]: fastlane version valid
12:34:26 [12:34:26]: ------------------------------
12:34:26 [12:34:26]: --- Step: default_platform ---
12:34:26 [12:34:26]: ------------------------------
12:34:26 [12:34:26]: Driving the lane 'ios develop'
12:34:26 [12:34:26]: [SHELL COMMAND]: chmod 777 ../pre-build.sh
12:34:26 [12:34:26]: [SHELL COMMAND]: ../pre-build.sh
12:34:27 [12:34:26]: -----------------
12:34:27 [12:34:26]: --- Step: ipa ---
12:34:27 [12:34:26]: -----------------
12:34:27 [12:34:26]: set -o pipefail && krausefx-ipa build -w "xcode/xxx.xcworkspace" -c "Alpha" -s "xxx" --clean -d "./build/" --ipa "xxx.ipa" --archive --verbose | xcpretty
12:34:27 [12:34:26]: [SHELL COMMAND]: set -o pipefail && krausefx-ipa build -w "xcode/xxx.xcworkspace" -c "Alpha" -s "xxx" --clean -d "./build/" --ipa "xxx.ipa" --archive --verbose | xcpretty
12:34:34 /Library/Ruby/Gems/2.0.0/gems/fastlane-1.2.2/lib/fastlane/actions/actions_helper.rb:93:in `sh_no_action': Exit status of command 'set -o pipefail && krausefx-ipa build -w "xcode/xxx.xcworkspace" -c "Alpha" -s "xxx" --clean -d "./build/" --ipa "xxx.ipa" --archive --verbose | xcpretty' was 256 instead of 0.  (RuntimeError)
12:34:34 error: invalid byte sequence in US-ASCII. Use --trace to view backtrace
12:34:34 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.2.2/lib/fastlane/actions/actions_helper.rb:72:in `sh'
12:34:34 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.2.2/lib/fastlane/actions/ipa.rb:64:in `run'
12:34:34 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.2.2/lib/fastlane/fast_file.rb:112:in `block (2 levels) in method_missing'
12:34:34 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.2.2/lib/fastlane/actions/actions_helper.rb:51:in `execute_action'
12:34:34 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.2.2/lib/fastlane/fast_file.rb:94:in `block in method_missing'
12:34:34 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.2.2/lib/fastlane/fast_file.rb:93:in `chdir'
12:34:34 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.2.2/lib/fastlane/fast_file.rb:93:in `method_missing'
12:34:34 	from (eval):52:in `block (3 levels) in parse'
12:34:34 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.2.2/lib/fastlane/runner.rb:35:in `call'
12:34:34 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.2.2/lib/fastlane/runner.rb:35:in `block in execute'
12:34:34 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.2.2/lib/fastlane/runner.rb:25:in `chdir'
12:34:34 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.2.2/lib/fastlane/runner.rb:25:in `execute'
12:34:34 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.2.2/lib/fastlane/lane_manager.rb:33:in `cruise_lane'
12:34:34 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.2.2/bin/fastlane:39:in `block (2 levels) in run'
12:34:34 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
12:34:34 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
12:34:34 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
12:34:34 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
12:34:34 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
12:34:34 	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
12:34:34 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.2.2/bin/fastlane:118:in `run'
12:34:34 	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.2.2/bin/fastlane:124:in `<top (required)>'
12:34:34 	from /usr/bin/fastlane:23:in `load'
12:34:34 	from /usr/bin/fastlane:23:in `<main>'
12:34:34 [12:34:32]: [SHELL]: error: invalid byte sequence in US-ASCII. Use --trace to view backtrace
12:34:34 [12:34:32]: Variable Dump:
12:34:34 [12:34:32]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios develop"}
12:34:34 [12:34:32]: Exit status of command 'set -o pipefail && krausefx-ipa build -w "xcode/xxx.xcworkspace" -c "Alpha" -s "xxx" --clean -d "./build/" --ipa "xxx.ipa" --archive --verbose | xcpretty' was 256 instead of 0. 
12:34:34 error: invalid byte sequence in US-ASCII. Use --trace to view backtrace
12:34:34 
12:34:34 [12:34:33]: fastlane finished with errors
12:34:34 
12:34:34 #######################################################################
12:34:34 # fastlane 1.2.3 is available. You are on 1.2.2.
12:34:34 # It is recommended to use the latest version.
12:34:34 # Update using 'sudo gem update fastlane'.
12:34:34 # To see what's new, open https://github.com/KrauseFx/fastlane/releases.
12:34:34 #######################################################################

It works fine if I run fastlane in the terminal on the same machine.

**Comment by KrauseFx** [comment]
@snarkdogg that's an easy fix, follow this reply: http://stackoverflow.com/a/17031697/445598 :+1:

**Comment by KrauseFx** [comment]
I updated the `ipa` action to make things clearer, also with the new `fastlane_core` this problem should be solved.

**Comment by cyupa** [comment]
First of all: amazing tool set!

I have a similar issue. My test lane failed with this error:
```
[10:21:11]: fastlane finished with errors
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.7.2/lib/fastlane/actions/actions_helper.rb:98:in `sh_no_action': Exit status of command 'set -o pipefail && xcodebuild -destination "name=iPhone 5s,OS=8.1" -destination-timeout "120" -scheme "MyProject" -workspace "MyProject.xcworkspace" test | xcpretty --color --report html --output "./build-dir/test-report.html" --screenshots --report junit --output "./build-dir/test-report.xml" --test' was 256 instead of 0.  (RuntimeError)
2015-07-12 10:20:58.277 xcodebuild[6672:107805] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ACCodeSnippetRepository.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-07-12 10:20:58:440 xcodebuild[6672:c0f] BBUncrustifyPlugin Version 2.1.1 loaded
.T.

	 Executed 2 tests, with 0 failures (0 unexpected) in 0.308 (0.310) seconds
/usr/local/lib/ruby/gems/2.2.0/gems/xcpretty-0.1.10/lib/xcpretty/reporters/html.rb:79:in `open': No such file or directory @ dir_initialize - build/reports (Errno::ENOENT)
	from /usr/local/lib/ruby/gems/2.2.0/gems/xcpretty-0.1.10/lib/xcpretty/reporters/html.rb:79:in `foreach'
	from /usr/local/lib/ruby/gems/2.2.0/gems/xcpretty-0.1.10/lib/xcpretty/reporters/html.rb:79:in `load_screenshots'
	from /usr/local/lib/ruby/gems/2.2.0/gems/xcpretty-0.1.10/lib/xcpretty/reporters/html.rb:66:in `write_report'
	from /usr/local/lib/ruby/gems/2.2.0/gems/xcpretty-0.1.10/lib/xcpretty/reporters/html.rb:43:in `finish'
	from /usr/local/lib/ruby/gems/2.2.0/gems/xcpretty-0.1.10/bin/xcpretty:84:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/xcpretty-0.1.10/bin/xcpretty:84:in `<top (required)>'
	from /usr/local/bin/xcpretty:23:in `load'
	from /usr/local/bin/xcpretty:23:in `<main>'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.7.2/lib/fastlane/actions/actions_helper.rb:72:in `sh'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.7.2/lib/fastlane/actions/xcodebuild.rb:201:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.7.2/lib/fastlane/actions/xcodebuild.rb:392:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.7.2/lib/fastlane/fast_file.rb:114:in `block (2 levels) in method_missing'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.7.2/lib/fastlane/actions/actions_helper.rb:51:in `execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.7.2/lib/fastlane/fast_file.rb:96:in `block in method_missing'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.7.2/lib/fastlane/fast_file.rb:95:in `chdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.7.2/lib/fastlane/fast_file.rb:95:in `method_missing'
	from (eval):35:in `block (3 levels) in parse'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.7.2/lib/fastlane/runner.rb:36:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.7.2/lib/fastlane/runner.rb:36:in `block in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.7.2/lib/fastlane/runner.rb:29:in `chdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.7.2/lib/fastlane/runner.rb:29:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.7.2/lib/fastlane/lane_manager.rb:33:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.7.2/bin/fastlane:39:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/runner.rb:68:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.4/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.7.2/bin/fastlane:128:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.7.2/bin/fastlane:134:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

I had the following in my Fastlane file:

    before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    cocoapods
    xctest(
      scheme: "Betalingsservice",
      destination: "name=iPhone 5s,OS=8.1",
      destination_timeout: 120, # increase device/simulator timeout, usually used on slow CI boxes
      reports: [{
        report: 'html',
        output: './build-dir/test-report.html',  # will use XCODE_BUILD_PATH/report, if output is not provided
        screenshots: 1
      },
      {
        report: 'junit',
        output: './build-dir/test-report.xml'
      }]
    )
    end

After I removed the HTML report, it worked. Any Idea why this might happen?
The suggested answer didn't fix it.

**Comment by KrauseFx** [comment]
@cyupa Does that mean the step fails when the `html` or `xml` file is already there and it can't be overwritten for some reason?

**Comment by cyupa** [comment]
@KrauseFx No html file there. If I leave only the junit report, it works. It fails only for the html report.

**Comment by craigmarvelley** [comment]
I just had this error - even though I specified output directories with both my html and xml outputs, it seems the tool still expects the default `build/report` directory to be present:

```
Executed 2 tests, with 0 failures (0 unexpected) in 0.006 (0.008) seconds
/Library/Ruby/Gems/2.0.0/gems/xcpretty-0.1.10/lib/xcpretty/reporters/html.rb:79:in `open': No such file or directory - build/reports (Errno::ENOENT)
```

**Comment by kdawgwilk** [comment]
Also Is there a way to generate the test report even when the tests fail? fastlane seems to exit before xcpretty can generate the report :(

**Comment by ms93** [comment]
@cyupa - deleting screenshots worked for me and @kdawgwilk I do have failing tests - it should still work:

        xctest(
     .
    .
    .
          report: 'html',
          output: './build-dir/test-report.html',  
          # screenshots: 1
        }
      ]
      )
