### ISSUE TITLE
Using different Provisioning profiles for Extensions (Target dependencies)

### ISSUE THREAD

**Issue by mathiasAichinger** [KrauseFx/fastlane#283]
Hi,
this is not really a fastlane problem, but a build problem in general. 

Is there way to specify the different provisioning profiles for the app and the extensions (target dependencies)? With "--embed" it doesn't work. We solved this problem by using xcconfigs to specify the provisioning profile, but this need to be done before building the app.

Actually we want to build once and after that we want to resign the app.

**Comment by joshdholtz** [comment]
@mathiasAichinger May I ask why you want to resign after the build? I actually haven't needed to do that before so more or less curious :innocent: Then maybe I can provide a better answer :blush:

**Comment by mathiasAichinger** [comment]
When we submit an app, we want to distribute the same binary (as the app store build) via HockeyApp for Internal testing. Additionally we also have an enterprise account for internal distribution. So we need to handle 3 different types of provision profiles for 3 different targets (app+widget+watch; and this for some different apps). *fun* ;)

**Comment by Khronoss** [comment]
Hi,
Did you found the solution of your problem ? It seems I have the...kinda...same troubleshot. I have an app with a WatchKit Extension and a Today Extension, but I can't figure out how to properly use Sigh before compiling my application with those 4 different targets (the app, the WatchKit Extension, the WatchKit App, and the Today Extension).
In fact, I use Ipa to build, and it uses ONLY the last provisioning profile that Sigh updated, and the build phase fails because the 3 other provisioning profiles are missing :s 
Have you any guess on that ?

**Comment by KrauseFx** [comment]
@mathiasAichinger @Khronoss is that the same issue https://github.com/KrauseFx/sigh/issues/131? If so, I'll close this issue to move further discussions to https://github.com/KrauseFx/sigh/issues/131.

**Comment by Khronoss** [comment]
Yup, I think that's the same issue that @mathiasAichinger is pointing out in the https://github.com/KrauseFx/sigh/issues/131 thread
