### ISSUE TITLE
Action update_project_provisioning corrupts .xcodeproj file

### ISSUE THREAD

**Issue by kohtenko** [KrauseFx/fastlane#324]
If you try to run lane like this: 
```
lane :beta do
   increment_build_number
   sigh(adhoc: true, output_path:"./fastlane/Certificates/")
   update_project_provisioning(
  		xcodeproj: "MyProject.xcodeproj",
   )
   ipa
   deliver(beta: true)
   commit_version_bump(message: 'Version Bump', xcodeproj: "MyProject.xcodeproj", force: true)
end
```

and run this lane twice, you will see error during second run like this:
```
Exit status of command 'cd /Users/user/Documents/MyApp && agvtool next-version -all' was 1536 instead of 0. 
There does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings.
```

If after this you manually change CURRENT_PROJECT_VERSION from Xcode, you'll see how Xcode removes `.xcodeproj` file and creates new one. After this you'll be able to run lane one more time.

**Comment by KrauseFx** [comment]
Is it a problem with the `increment_build_number` or `update_project_provisioning`? 

I use `update_project_provisioning` without committing the changes afterwards, so that might be the reason.

Take a look at the [MindNode Example Setup](https://github.com/fastlane/examples/blob/master/MindNode/Fastfile#L7-L35) of how I usually use it :+1:

**Comment by kohtenko** [comment]
This is a `update_project_provisioning` issue, not `increment_build_number`. Approach in your example works, probably git reset is the only way now.
