### ISSUE TITLE
Jenkins: security: cert import failed: A default keychain could not be found

### ISSUE THREAD

**Issue by nklausni** [KrauseFx/fastlane#360]
When using fastlane / sigh on jenkins i got an error on saving provisioning profiles in keychain, because of no default keychain is set for jenkins user. How can I solve this problem?

Btw: Works well on local machine, seems to be just a problem on build server

```
sigh(
          app_identifier: "APP_IDENTIFIER_REMOVED", 
          output_path: "./fastlane/provisioning-profiles",
          development: true
      )
```

```
[14:45:17]: ------------------
[14:45:17]: --- Step: sigh ---
[14:45:17]: ------------------
[14:45:17]: Starting login
Logging spaceship web requests to '/tmp/spaceship.log'
[14:45:19]: Successfully logged in
[14:45:21]: Found 1 matching profile(s)
[14:45:21]: Downloading provisioning profile...
[14:45:22]: Successfully downloaded provisioning profile...
security: cert import failed: A default keychain could not be found.
security: problem decoding
```

**Comment by KrauseFx** [comment]
The easiest fix is to install Jenkins using homebrew and run it as the standard Mac OS user. I have no experience with setting up `sigh` with its Jenkins user.

**Comment by nklausni** [comment]
Ok, thank you. I'll try this :)

**Comment by besi** [comment]
I had a similar problem using Xcode Server. 
What I did was create a new Keychain for the user. It was important to put the keychain in the proper file location:

```bash
sudo su -m _xcsbuildd
mkdir -p ~/Library/Keychains/
security create-keychain -p password ~/Library/Keychains/Login.keychain
security login-keychain -d user -s ~/Library/Keychains/Login.keychain 
security default-keychain -s $KEYCHAIN
```

Now when I execute the `sigh` command the keychain is found and the certificates downloaded.

**Comment by KrauseFx** [comment]
@nklausni Did you resolve this issue? Feel free to re-open it if you have any more troubles

**Comment by KrauseFx** [comment]
Also, thanks @besi for sharing your solution :+1:

**Comment by nklausni** [comment]
Issue fixed, solved with your "new user" solution. thanks :)

**Comment by natanrolnik** [comment]
I wrote an article/tutorial that includes the Keychain/Certificate handling in a Continuous Integration service, that may help people who reach this issue: http://natanrolnik.me/2015/10/21/introduction-to-fastlane-and-integrating-it-with-circleci-to-deploy-beta-with-crashlytics-fabric/

**Comment by yuriferretti-luizalabs** [comment]
@natanrolnik Great tutorial, it helped me a lot! I just found one issue, when importing the certificates and keys I had to import `.cer` file before`.p12` key  because it was raising an exception of "already installed certificate". After changing the order it worked as expected.

**Comment by KrauseFx** [comment]
Also, check out [match](https://github.com/fastlane/match) which solves a lot of these problems for you :+1:

**Comment by lakamsani** [comment]
match is going to try and access the certs from login keychain of the jenkins user if running as launch daemon. In my environment (jenkins 2.3 running as jenkins users on OS X El Capitan, fastlane 1.89.0) code signing was failing. The fix was to unlock the login keychain before running fastlane. Something like this:

1.  install this plugin https://wiki.jenkins-ci.org/display/JENKINS/Mask+Passwords+Plugin
2.  setup a global password variable called KC_PWD so multiple jenkins projects can use the same.
3.  on each jenkins project config: check,  Build Environment -> Mask passwords (and enable global passwords)
4.  add an Execute Shell build step that looks like this:

- security unlock-keychain -p "${KC_PWD}" "$HOME/Library/Keychains/login.keychain"
- fastlane jenkins (or whatever lane you want to run as part of CI)

It will print something like this before running the lane and will sign the code fine.
 security unlock-keychain -p ******** /Users/Shared/Jenkins/Library/Keychains/login.keychain

I think there is a unlock_keychain task in fastlane but was  sure how to mask the password using that one. 

Given that codesign and security are the only tools that need access I did NOT have to do this: 
http://stackoverflow.com/questions/577750/running-xcodebuild-from-a-forked-terminal/12235462#12235462

**Comment by TKBurner** [comment]
@lakamsani Thanks for sharing that info! The unlock_keychain action using an ENV variable for the password, so it will be stored somewhere in your repo in plain text.

**Comment by lakamsani** [comment]
In my setup described above, it is actually stored by the Jenkins masked password plugin  in its config file com.michelin.cio.hudson.plugins.maskpasswords.MaskPasswordsConfig.xml encrypted. Not plain text. I guess we could skip the login chain and use custom keychains but even they need a password and need to be stored somewhere.
