### ISSUE TITLE
Support pod update instead of pod install

### ISSUE THREAD

**Issue by ex3ndr** [KrauseFx/fastlane#706]
Very useful for ci to continuously update all dependencies.

**Comment by KrauseFx** [comment]
@ex3ndr I don't think that's a good idea to be honest. If you really want to do it, just add `sh "pod update"` to your `Fastfile`

**Comment by xfreebird** [comment]
@ex3ndr, as @KrauseFx said that is not a good idea, because it will not install new pods from the ```Podfile```. But we might need to have an update option for ```cocoapods```, in cases when we want to update the installed pods. https://github.com/CocoaPods/CocoaPods/issues/760#issuecomment-46300500

```pod install``` this is to be used every time you edit your Podfile to add a new pod to it (or remove one from it).

```pod update``` CocoaPods will update every pod listed in your Podfile to the latest version possible.

**Comment by KrauseFx** [comment]
I'll close this issue for now :+1: @ex3ndr feel free to re-open if you have any additional questions.
